# dependencies / links
highlighter: rouge
permalink: pretty
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM

# setup
# access this data with site.date. eg: {{ site.title }}
# baseurl: https://molecule.github.io

title: Molly Nicholas
dev_url: localhost:4000
port: 4013
keywords: Molly Jane Nicholas, berkeley, human computer interaction, phd, performance, puppeteering, puppet, stage, theatre, production, performing, computer science, hci, computers, interfaces, interface design, user experience, user interfaces, camping, hiking, california, colorado, california hiking, colorado hiking, campsite, tents, outdoors, puppeteer
desc: > 
  Welcome to Molly's site, with information about her research
  in Human Computer Interaction, her work in the performing arts, and
  her many hiking and camping adventures.

# owner
author:
  name: Molly Jane Nicholas
  email: molecule@berkeley.edu
  github: https://github.com/molecule
  twitter: https://twitter.com/FakepaperClips

# site data
collections:
  post: {output: true}
  project: {output: true}
  recipes: 
    output: true  #permalink: /:collection/:name/
  trips: {output: true}
